# Generated by Django 4.2.6 on 2023-11-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=200, verbose_name='Driver Name')),
                ('date', models.CharField(max_length=200, verbose_name='Date')),
                ('driverAddress', models.CharField(max_length=200, verbose_name='Driver Address')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN #')),
                ('managerName', models.CharField(max_length=200, verbose_name='Manager Name')),
                ('stockNum', models.CharField(max_length=200, verbose_name='Stock Number')),
                ('codriver', models.CharField(blank=True, max_length=200, verbose_name='Codriver')),
                ('milesDriven', models.CharField(max_length=200, verbose_name='Miles Driven')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
